# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs :
  creat_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: building a bucket 
          command: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name "${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete        

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: the id of the pipeline that was responsible for the last prod
          command: |
            aws cloudformation \
              list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
              --no-paginate --output pipeline_id.txt   

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
         name: deploy an infrastructure 
         command: |
          aws cloudformation deploy \
          --template-file cloudfront.yml \
          --stack-name production-distro \
          --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"   

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli 
    steps:
      - run: OldPipelineID=$'cat ~/Git/Promote/pipeline_id,txt'
      - run: aws s3 rm "s3://${OldPipelineID}" --recursive
      - run: aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
                      
workflows:

  deploy_green_remove_blue:
    jobs:
      - creat_and_deploy_front_end:
          context : AWS
      - get_last_deployment_id:
          requires:
            - creat_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            -  promote_to_production 
